version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gym_postgres_db
    environment:
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: gympass
      POSTGRES_DB: gymdb
    ports:
      - "5432:5432"
    volumes:
      - gymdata:/var/lib/postgresql/data

volumes:
  gymdata:
